version: '3'

services:
 
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ~/.impulse_core/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  impulse-local:
    image: python:3.9-slim
    volumes:
      - ..:/impulse
      - .:/app
    ports:
      - 8501:8501
    working_dir: /app
    command: /bin/bash -c "cd app && pip install -r requirements.txt && streamlit run app.py && cd /impulse && pip install --no-cache-dir --force-reinstall ."
  